#define MAX_PLAYERS 64
#define MAX_BONES 128
#define BACKTRACK_TICKS 64
#define RESOLVEBASECOUNT 1
#define MULTIPOINT_COUNT 8
#define NUM_THREADS 12
#define RESOLVE_ANGLE_STEP 60
#define RESOLVE_BRUTEFORCE_STEP 30
