#!/bin/sh

sudo kill -STOP $(pidof steam)

#Credit: Aixxe @ aixxe.net
sudo gdb -n -q -batch \
    -ex "attach $(pidof csgo_linux64)" \
    -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
    -ex "set \$dlclose = (int(*)(void*)) dlclose" \
    -ex "set \$dlerror = (char*(*)(void)) dlerror" \
    -ex "set \$library = \$dlopen(\"$(pwd)/build/libm0dular.so\", 1)" \
    -ex "call \$dlerror()" \
    -ex "call \$dlclose(\$library)" \
    -ex "call \$dlclose(\$library)" \
    -ex "detach" \
    -ex "quit"

sudo kill -CONT $(pidof steam)

